title: Techie Bus
tagline: Mobile makerspace in Central Massachusetts & Worcester
description: STE(A)M Education brought to your classroom or library
url: http://techiebus.com

socialMediaImage: /images/logo.png
logo: /images/logo.png
twitter:
facebook:
instagram:
mailchimpURI: https://techiebus.us17.list-manage.com/subscribe/post?u=2e811db3896c40e5e80ba0c34&amp;id=bd399f10f2
mailchimpAntiSpamCode: b_2e811db3896c40e5e80ba0c34_bd399f10f2
